[frontend] feat: diaryList page layout
JongHyeok-Park/CapstoneDesign2 pull request #1
Opened 2024-03-30 16:16 UTC by thanhhien234

- 일기 목록 페이지의 레이아웃을 구현했는데 나중에 css 수정할 예정입니다

2024-04-01 16:16 UTC, thanhhien234 commented
navigation bar 추가 구현했습니다. 일기 목록 페이지의 css도 수정했습니다

2024-04-04 07:47 UTC, JongHyeok-Park requested changes
확인해보고 안되는 거면 말해주세여~ 저도 틀릴 수 있으니..

2024-04-04 07:47 UTC, JongHyeok-Park commented on frontend/stt_diary/src/components/NavigationItem.js
여기엔 onClick 없어도 동작할 것 같은데요?

2024-04-04 07:47 UTC, JongHyeok-Park commented on frontend/stt_diary/src/components/NavigationMenu.js
여기에 onClick이 있네요.

2024-04-04 07:47 UTC, JongHyeok-Park commented on frontend/stt_diary/src/components/NavigationMenu.js
그리고 activePage는 나중에 Redux로 전역상태로 뺍시다. NavigationItem component 안에서 불러오면 되겠네요.

2024-04-04 07:47 UTC, JongHyeok-Park commented on frontend/stt_diary/src/components/NavigationMenu.js
만약 NavigationItem에서 onClick 빼서 동작 안 되면 path를 navigate안에 변수로 넣어도 될 것 같은대용?
navigate('/' + path); 같은 식으로?

2024-04-04 07:59 UTC, JongHyeok-Park commented
그리고 data에 map 하기 전에 length check 해봐야겠네요. data가 없으면 error 발생할테니까.

2024-04-05 16:47 UTC, thanhhien234 commented
수정했습니다. 확인해주세요~

2024-04-08 07:38 UTC, JongHyeok-Park requested changes
이것만 하면 진짜 끝인 것 같습니다.

2024-04-08 07:38 UTC, JongHyeok-Park commented on frontend/stt_diary/src/routes/DiaryListData.js
> +        date: "2024년 3월 25일",
그 제가 date format을 저렇게 적긴 했는데 API에서 response 는 yyyy-mm-dd 인 것 같아서 바꿔서 테스트 해야할 것 같네요. 쏘리..

2024-04-08 07:38 UTC, JongHyeok-Park commented on frontend/stt_diary/src/routes/DiaryList.js
> +              <option value="">1월</option>
여기 Select에 들어가는 Option들도 diary object list에서 값 가져와서 넣어야 할 것 같네요.

2024-04-08 07:38 UTC, JongHyeok-Park commented on frontend/stt_diary/src/routes/DiaryList.js
> +                  <div className="diary-date">{item.date}</div>
여기 date도 format이 다르면 그냥 넣으면 안 되겠네요.

2024-04-11 15:36 UTC, JongHyeok-Park approved these changes

2024-04-11 16:05 UTC, merged