[frontend] feat: detailDiary, add confirm, change loading message
JongHyeok-Park/CapstoneDesign2 pull request #18
Opened 2024-05-27 15:34 UTC by thanhhien234

2024-05-28 08:00 UTC, JongHyeok-Park requested changes
그 다음엔 뭐 작업했는지 PR내용 좀 적어줘요.

2024-05-28 08:00 UTC, JongHyeok-Park commented on frontend/stt_diary/src/routes/DiaryList.js
> +        console.error('Error:', error);
로그인 안 했을 때 에러 숨기려고 한 것 같은데 위에 if문 넣어서 token 있는지 확인하고 하면 되지 않을까요
이러면 에러 자체가 안 뜰텐데

2024-05-30 00:44 UTC, thanhhien234 commented on frontend/stt_diary/src/routes/DiaryList.js
> +        console.error('Error:', error);
수정했습니다

2024-05-30 04:51 UTC, JongHyeok-Park approved these changes

2024-05-30 04:53 UTC, merged